export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const LOG_ERROR = "LOG_ERROR";
export const LOG_SUCCESS = "LOG_SUCCESS";

export const TASK_LIST_REQUEST = "TASK_LIST_REQUEST";
export const TASK_LIST_REFRESH = "TASK_LIST_REFRESH";
export const TASK_LIST_SUCCESS = "TASK_LIST_SUCCESS";
export const TASK_LIST_FAIL = "TASK_LIST_FAIL";
export const TASK_LIST_FILTER = "TASK_LIST_FILTER";
export const TASK_LIST_SEARCH = "TASK_LIST_SEARCH";

export const TASK_DETAIL_REQUEST = "TASK_DETAIL_REQUEST";
export const TASK_DETAIL_SUCCESS = "TASK_DETAIL_SUCCESS";
export const TASK_DETAIL_RESET = "TASK_DETAIL_RESET";
export const TASK_DETAIL_FAIL = "TASK_DETAIL_FAIL";

export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
